'use client';
import { useState } from 'react';
import {stageFiles,cancelStagedFiles} from '@/lib/upload-client';
import {MAX_INLINE_BYTES} from '@/lib/upload-limits';
import { useRouter } from 'next/navigation';
import { Info, RefreshCw } from 'lucide-react';
import type { Source } from '@/types/domain';
import type { IsoWeek } from '@/lib/iso-week';
import { SourceUploadCard, type UploadSource } from './SourceUploadCard';
const sources:UploadSource[]=[
 {name:'CREDENCIALIZACION',title:'CREDENCIALIZACIÓN',description:'Tarjetas emitidas por perfil',formatLabel:'Reporte semanal .xlsx o consolidado .xlsx/.csv',extensions:['xlsx','csv']},
 {name:'OXXO',title:'OXXO',description:'Operaciones y recargas electrónicas',formatLabel:'Archivo esperado: .DAT',extensions:['dat']},
 {name:'CAUS',title:'CAUS',description:'Ventas de tarjetas y recargas',formatLabel:'Archivo esperado: .xlsx o .csv',extensions:['xlsx','csv']},
 {name:'VALIDACIONES',title:'VALIDACIONES BEA',description:'Uso de tarjetas del sistema BEA',formatLabel:'Archivo esperado: .xlsx o .csv',extensions:['csv','xlsx']},
];
type Result={source:Source;year:number;week:number;records:number;count:number;amountCents:number;duplicate:boolean;files:{id:string;name:string}[]};
export function UploadWorkspace({cutoff}:{cutoff:IsoWeek}){
 const router=useRouter();const [files,setFiles]=useState<Partial<Record<Source,File[]>>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [year,setYear]=useState(cutoff.year);const [week,setWeek]=useState(cutoff.week);const [results,setResults]=useState<Result[]>([]);const [progress,setProgress]=useState('');
 function select(source:UploadSource,incoming:File[]){if(busy)return;const accepted=incoming.filter(f=>source.extensions.includes(f.name.split('.').pop()?.toLowerCase()??''));setError(accepted.length!==incoming.length?`En ${source.title} solo se admiten ${source.extensions.map(e=>'.'+e).join(', ')}. Guarda los .xls como .xlsx.`:'');setFiles(previous=>({...previous,[source.name]:[...(previous[source.name]??[]),...accepted]}));}
 const count=Object.values(files).reduce((n,list)=>n+(list?.length??0),0);
 async function process(){setError('');setResults([]);setBusy(true);try{for(const source of sources){const selected=files[source.name]??[];if(!selected.length)continue;setProgress(`Procesando ${source.title}…`);const form=new FormData();form.set('source',source.name);form.set('year',String(year));form.set('week',String(week));selected.forEach(f=>form.append('files',f));const large=selected.reduce((sum,f)=>sum+f.size,0)>MAX_INLINE_BYTES;const ids=large?await stageFiles(source.name,year,week,selected,setProgress):null;setProgress(`Procesando ${source.title}…`);let response:Response;try{response=await fetch(large?'/api/semanas/cargas/procesar':'/api/semanas/procesar',{method:'POST',...(large?{headers:{'Content-Type':'application/json'},body:JSON.stringify({source:source.name,year,week,ids})}:{body:form})});}finally{if(ids)await cancelStagedFiles(ids);}const data=await response.json();if(!response.ok)throw new Error(`${source.title}: ${data.error||'No fue posible procesar.'}`);setResults(previous=>[...previous,data.result]);setFiles(previous=>({...previous,[source.name]:[]}));router.refresh();}}catch(e){setError(e instanceof Error?e.message:'No fue posible procesar.');}finally{setBusy(false);setProgress('');}}
 return <><ol className="steps" aria-label="Pasos de actualización"><li className={!busy&&!results.length?'current':''}><b>1</b> Seleccionar archivos</li><li className={busy?'current':''}><b>2</b> Procesar semana</li><li className={results.length?'current':''}><b>3</b> Revisar resultados</li></ol><section className="panel weekly-period"><label>Año ISO<input type="number" min={2000} max={2100} value={year} disabled={busy} onChange={e=>setYear(Number(e.target.value))}/></label><label>Semana ISO<input type="number" min={1} max={53} value={week} disabled={busy} onChange={e=>setWeek(Number(e.target.value))}/></label><p>Selecciona una semana cerrada. Cada fuente se procesa por separado; una semana existente se conserva.</p></section><fieldset disabled={busy} className="upload-fieldset"><div className="upload-grid">{sources.map(source=><SourceUploadCard key={source.name} source={source} files={files[source.name]??[]} onSelect={incoming=>select(source,incoming)} onRemove={index=>{if(!busy)setFiles(previous=>({...previous,[source.name]:(previous[source.name]??[]).filter((_,i)=>i!==index)}));}}/>)}</div></fieldset>{error&&<p className="error-text" role="alert">{error}</p>}<div className="notice"><Info size={18}/><p><strong>Original y CSV conservados en Drive.</strong> Se valida el periodo antes de guardar. Validaciones cuenta tarjetas únicas con la base histórica de primera validación. Límite: 50 MB y ocho archivos por fuente; CAUS y credencialización admiten un reporte por semana. Un consolidado de credencialización debe conservar las cifras de las semanas anteriores.</p></div><section className="panel process-summary"><div><h2>Procesamiento del periodo</h2><p aria-live="polite">{progress||`${count} ${count===1?'archivo seleccionado':'archivos seleccionados'} · ${year}-S${String(week).padStart(2,'0')}`}</p></div><button className="button primary" disabled={busy||!count} onClick={process}><RefreshCw size={16}/>{busy?'Procesando…':'Procesar semana'}</button></section>{results.length>0&&<section className="panel weekly-results" aria-live="polite"><h2>Resultados guardados</h2>{results.map(r=><article key={r.source}><h3>{r.source} · {r.year}-S{r.week}</h3><p>{r.duplicate?'La misma carga ya estaba procesada; no se duplicó.':`${r.records.toLocaleString('es-MX')} registros procesados. Dashboard actualizado.`}</p><p>{r.source==='CREDENCIALIZACION'?`${r.count.toLocaleString('es-MX')} tarjetas emitidas en la semana`:r.source==='VALIDACIONES'?`${r.count.toLocaleString('es-MX')} tarjetas únicas acumuladas`:`Ingreso semanal: ${(r.amountCents/100).toLocaleString('es-MX',{style:'currency',currency:'MXN'})}`}</p><ul>{r.files.map(f=><li key={f.id}><a href={`https://drive.google.com/file/d/${f.id}/view`} target="_blank" rel="noreferrer">{f.name}</a></li>)}</ul></article>)}</section>}</>;
}
