'use client';
import { useState } from 'react';
import type {Goals} from '@/types/domain';
import type { WeeklyRow } from '@/lib/history-model';
type Series={name:string;color:string;rows:WeeklyRow[];metric:'count'|'amountCents';cumulative?:boolean;dashed?:boolean};
export function ReferenceChart({title,series,goal,alignWeeks=false,showTotal=false}:{title:string;series:Series[];goal?:number;alignWeeks?:boolean;showTotal?:boolean}){
 const [activeKey,setActiveKey]=useState<number|null>(null);
 const key=(r:WeeklyRow)=>alignWeeks?r.week:r.year*100+r.week;
 const keys=[...new Set(series.flatMap(s=>s.rows.map(key)))].sort((a,b)=>a-b);
 const plotted=series.map(s=>({...s,points:s.rows.map((r,i)=>({key:key(r),value:s.cumulative?s.rows.slice(0,i+1).reduce((n,row)=>n+row[s.metric],0):r[s.metric]}))}));
 const max=Math.max(1,goal||0,...plotted.flatMap(s=>s.points.map(p=>p.value))),x=(k:number)=>65+keys.indexOf(k)*810/Math.max(1,keys.length-1),y=(v:number)=>270-v/max*230;
 const active=activeKey!==null&&keys.includes(activeKey)?activeKey:null;
 const label=(k:number)=>alignWeeks?`Semana ${k}`:`${Math.floor(k/100)} · Semana ${k%100}`;
 const format=(v:number,metric:Series['metric'])=>metric==='amountCents'?(v/100).toLocaleString('es-MX',{style:'currency',currency:'MXN'}):v.toLocaleString('es-MX');
 const totalAt=(k:number|null)=>{const points=plotted.map(s=>s.points.find(p=>p.key===k));return showTotal&&points.every(Boolean)?format(points.reduce((sum,p)=>sum+p!.value,0),'amountCents'):null;};
 const activePoints=plotted.flatMap(s=>s.points.filter(p=>p.key===active).map(p=>({name:s.name,color:s.color,value:format(p.value,s.metric)})));
 return <article className="panel chart-panel"><h3>{title}</h3>{!keys.length?<p>Sin datos para este periodo.</p>:<><div className="interactive-chart" onMouseLeave={()=>setActiveKey(null)}><svg viewBox="0 0 920 340" role="group" aria-label={title} style={{width:'100%',minHeight:220}}>{Array.from({length:5},(_,i)=>{const v=max*i/4;return <g key={i}><line x1="65" x2="875" y1={y(v)} y2={y(v)} stroke="#ddd" strokeDasharray="4 4"/><text x="58" y={y(v)+4} textAnchor="end" fontSize="12">{(v/(series[0]?.metric==='amountCents'?100:1)).toLocaleString('es-MX',{maximumFractionDigits:0,notation:'compact'})}</text></g>;})}{goal&&<g><line x1="65" x2="875" y1={y(goal)} y2={y(goal)} stroke="#DC7F37" strokeWidth="3" strokeDasharray="9 5"/><text x="70" y={y(goal)-8} fontSize="12">Meta {goal.toLocaleString('es-MX')}</text></g>}{plotted.map(s=><g key={s.name}><polyline fill="none" stroke={s.color} strokeWidth="3" strokeDasharray={s.dashed?'8 5':undefined} points={s.points.map(p=>`${x(p.key)},${y(p.value)}`).join(' ')}/>{s.points.map(p=><circle key={p.key} cx={x(p.key)} cy={y(p.value)} r="4" fill={s.color}><title>{s.name} · {p.key}: {(p.value/(s.metric==='amountCents'?100:1)).toLocaleString('es-MX')}</title></circle>)}</g>)}{keys.filter((_,i)=>i%Math.max(1,Math.ceil(keys.length/12))===0||i===keys.length-1).map(k=><text key={k} x={x(k)} y="294" textAnchor="middle" fontSize="12">{alignWeeks?`S${k}`:`${Math.floor(k/100)}-S${String(k%100).padStart(2,'0')}`}</text>)}{active!==null&&<line x1={x(active)} x2={x(active)} y1="30" y2="270" stroke="#960E53" strokeDasharray="4 4" opacity="0.45"/>}{keys.map((k,i)=>{const left=i===0?45:(x(keys[i-1])+x(k))/2,right=i===keys.length-1?895:(x(k)+x(keys[i+1]))/2;return <rect key={k} x={left} y="25" width={right-left} height="260" fill="transparent" tabIndex={0} role="button" aria-label={`${label(k)}. ${plotted.flatMap(s=>s.points.filter(p=>p.key===k).map(p=>`${s.name}: ${format(p.value,s.metric)}`)).join('. ')}${totalAt(k)?`. Total: ${totalAt(k)}`:''}`} onMouseEnter={()=>setActiveKey(k)} onFocus={()=>setActiveKey(k)} onBlur={()=>setActiveKey(null)} onClick={()=>setActiveKey(k)} onKeyDown={e=>{if(e.key==='Escape')setActiveKey(null);else if(e.key==='Enter'||e.key===' '){e.preventDefault();setActiveKey(k);}}}/>;})}</svg>{active!==null&&<div className="chart-tooltip" role="status" style={{left:`clamp(130px, ${x(active)/920*100}%, calc(100% - 130px))`}}><strong>{label(active)}</strong>{activePoints.map(p=><div key={p.name}><span style={{color:p.color}}>● {p.name}</span><b>{p.value}</b></div>)}{totalAt(active)&&<div style={{borderTop:'1px solid var(--border)',marginTop:6,paddingTop:8}}><strong>Total</strong><b>{totalAt(active)}</b></div>}</div>}</div><p>{series.map(s=><span key={s.name} style={{color:s.color,marginRight:18}}>● {s.name}</span>)}</p></>}</article>;
}
export function ProfileChart({rows,goals}:{rows:WeeklyRow[];goals:Goals}){const totals:Record<string,number>={};for(const row of rows)for(const [name,n]of Object.entries(row.profiles||{})){const profile=name==='TARIFA GENERAL'?'PREPAGO':name==='DISCAPACITADO'?'DISCAPACIDAD':name;totals[profile]=(totals[profile]||0)+n;}const names=['PREPAGO','ESTUDIANTE','TERCERA EDAD','DISCAPACIDAD','GOBIERNO'] as const;const max=Math.max(1,...Object.values(totals),...Object.entries(goals).filter(([name])=>name!=='general').map(([,value])=>value));return <article className="panel chart-panel"><h3>Tarjetas emitidas por perfil vs meta</h3>{names.map((name,i)=><div key={name} style={{margin:'22px 0'}}><p>{name}: <strong>{(totals[name]||0).toLocaleString('es-MX')}</strong>{name==='GOBIERNO'?' · Sin meta asignada':` · Meta ${goals[name].toLocaleString('es-MX')}`}</p><div style={{position:'relative',height:25,background:'#f5f5f5'}}><div style={{height:25,width:`${(totals[name]||0)/max*100}%`,background:i%2?'#DC7F37':'#960E53'}}/>{name!=='GOBIERNO'&&<span title={`Meta ${goals[name]}`} style={{position:'absolute',left:`${goals[name]/max*100}%`,top:0,transform:'translateX(-50%)'}}>★</span>}</div></div>)}</article>;}
