import 'server-only';
import { createHash } from 'node:crypto';
import { causRows, credentialRows, credentialConsolidatedCsv, validationReferenceCsv } from '@/lib/history-excel';
import { db } from './db';
import { driveRequest, accessToken } from './drive';
import { lastClosedWeek } from '@/lib/iso-week';
import { parseSnapshot, weekKey, historySources, type HistorySource, type WeeklyRow, type DatasetView } from '@/lib/history-model';
import type { DriveEntry } from '@/lib/drive-model';
import { latestSharedSnapshots } from '@/lib/shared-history';
import { sharedDriveFolders, sharedUsersFilter } from './shared-history';
const names:Record<HistorySource,string[]>={OXXO:['indicadores_semanales_iso_tarjeta04.csv'],CAUS:['ingreso_caus_por_semana.csv'],CREDENCIALIZACION:['tarjetas_emitidas_long_consolidado.xlsx','credenciales_emitidas_long_consolidado.xlsx','credenciales_emitidas_long_consolidado.csv'],VALIDACIONES:['tarjetas_acumuladas_por_semana_BEA.csv','tarjetas_acumuladas_por_semana_BEA_OPTIMIZADO.csv']};
export async function historyData(userId:string):Promise<DatasetView[]>{
 const folders=await sharedDriveFolders(userId,historySources);
 if(!folders.length)return [];
 const datasets=await db().historicalDataset.findMany({where:{user:sharedUsersFilter(),OR:folders.map(folder=>({source:folder.type,folderId:folder.folderId}))},orderBy:[{importedAt:'desc'},{id:'desc'}]});
 return latestSharedSnapshots(folders,datasets).map(d=>({source:d.source as HistorySource,rows:d.rows as unknown as WeeklyRow[],warnings:d.warnings as string[],importedAt:d.importedAt.toISOString()}));
}
async function download(userId:string,file:DriveEntry,key?:string){if(Number(file.size)>20*1024*1024)throw new Error('El archivo excede el límite de importación de 20 MB.');const token=await accessToken(userId);const headers:Record<string,string>={Authorization:`Bearer ${token}`};if(key)headers['X-Goog-Drive-Resource-Keys']=`${file.id}/${key}`;const response=await fetch(`https://www.googleapis.com/drive/v3/files/${file.id}?alt=media&supportsAllDrives=true`,{headers,cache:'no-store',signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error('No fue posible descargar el archivo autorizado.');const chunks:Uint8Array[]=[];let total=0;for await(const chunk of response.body!){total+=chunk.length;if(total>20*1024*1024)throw new Error('Archivo demasiado grande.');chunks.push(chunk);}return Buffer.concat(chunks);}
export async function importHistorySource(userId:string,source:HistorySource){if(!historySources.includes(source))throw new Error('Fuente inválida.');const cutoff=lastClosedWeek();const folder=await db().driveFolder.findUnique({where:{userId_type:{userId,type:source}}});if(!folder)throw new Error('Selecciona primero la carpeta de esta fuente.');const files:DriveEntry[]=[];let page:string|undefined;
 do{const result=await driveRequest<{files:DriveEntry[];nextPageToken?:string}>(userId,'files',{q:`trashed=false and '${folder.folderId}' in parents`,fields:'files(id,name,size,modifiedTime,mimeType),nextPageToken',supportsAllDrives:'true',includeItemsFromAllDrives:'true',pageSize:'100',...(page?{pageToken:page}:{})},{id:folder.folderId,key:folder.resourceKey||undefined});files.push(...result.files);page=result.nextPageToken;if(files.length>1000)throw new Error('Esta carpeta requiere importación por lotes.');}while(page);
 const matches=names[source].flatMap(name=>files.filter(f=>f.name===name));let rows:WeeklyRow[]=[];const warnings:string[]=[];const provenance:{id:string;name:string;hash:string;modifiedTime:string|null}[]=[];
 if(matches.length){const preferred=matches.filter(f=>f.name===matches[0].name);if(preferred.length!==1)throw new Error('Hay dos consolidados con el mismo nombre; selecciona una ubicación inequívoca.');const file=preferred[0],buffer=await download(userId,file,folder.resourceKey||undefined);rows=parseSnapshot(source,source==='CREDENCIALIZACION'&&file.name.endsWith('.xlsx')?await credentialConsolidatedCsv(buffer):new TextDecoder('utf-8',{fatal:true}).decode(buffer),cutoff);provenance.push({id:file.id,name:file.name,hash:createHash('sha256').update(buffer).digest('hex'),modifiedTime:file.modifiedTime||null});}
 else if(source==='CAUS'){const hashes=new Set<string>(),weeks=new Map<number,WeeklyRow>();const candidates=files.filter(f=>/\.xlsx$/i.test(f.name)&&!f.name.startsWith('~$'));if(candidates.length>100)throw new Error('CAUS necesita importación por lotes.');for(const file of candidates){const buffer=await download(userId,file,folder.resourceKey||undefined);const hash=createHash('sha256').update(buffer).digest('hex');if(hashes.has(hash))continue;hashes.add(hash);try{const row=await causRows(buffer,cutoff);if(!row)continue;if(weeks.has(weekKey(row)))throw new Error('Dos archivos CAUS distintos cubren la misma semana; revisar versiones.');weeks.set(weekKey(row),row);provenance.push({id:file.id,name:file.name,hash,modifiedTime:file.modifiedTime||null});}catch(error){if(error instanceof Error&&error.message.startsWith('Dos archivos'))throw error;warnings.push(`${file.name}: ${error instanceof Error?error.message:'Archivo no válido.'}`);}}rows=[...weeks.values()].sort((a,b)=>weekKey(a)-weekKey(b));}
 else if(source!=='CREDENCIALIZACION') throw new Error(`No está disponible el consolidado ${names[source][0]} en la carpeta configurada.`);
 if(source==='CREDENCIALIZACION'&&!provenance.some(file=>file.name.endsWith('long_consolidado.xlsx'))){
 const weeks=new Map(rows.map(row=>[weekKey(row),row])),hashes=new Set<string>(),rawWeeks=new Map<number,string>();const candidates=files.filter(f=>/\.xlsx$/i.test(f.name)&&!f.name.startsWith('~$')&&!f.name.startsWith('credenciales_emitidas_long_consolidado'));if(candidates.length>100)throw new Error('Esta carpeta requiere importación por lotes.');
 for(const file of candidates){try{const buffer=await download(userId,file,folder.resourceKey||undefined),hash=createHash('sha256').update(buffer).digest('hex');if(hashes.has(hash))continue;hashes.add(hash);const row=await credentialRows(buffer,cutoff);if(!row)continue;const key=weekKey(row);if(rawWeeks.has(key))throw new Error('Dos archivos de emisión distintos cubren la misma semana.');rawWeeks.set(key,file.id);const previous=weeks.get(key);if(previous&&previous.count!==row.count)warnings.push(`${file.name}: difiere del consolidado; se conserva el consolidado para revisión.`);else{weeks.set(key,row);provenance.push({id:file.id,name:file.name,hash,modifiedTime:file.modifiedTime||null});}}catch(error){if(error instanceof Error&&error.message.startsWith('Dos archivos'))throw error;warnings.push(`${file.name}: ${error instanceof Error?error.message:'Archivo no válido.'}`);}}
 rows=[...weeks.values()].sort((a,b)=>weekKey(a)-weekKey(b));
 }
 if(source==='VALIDACIONES'){
 const credentialFolder=await db().driveFolder.findUnique({where:{userId_type:{userId,type:'CREDENCIALIZACION'}}});
 if(credentialFolder){const metadata=await driveRequest<{parents?:string[]}>(userId,`files/${credentialFolder.folderId}`,{fields:'parents'});for(const parent of metadata.parents||[]){const references=await driveRequest<{files:DriveEntry[]}>(userId,'files',{q:`trashed=false and '${parent}' in parents and name='tarjetas_acumuladas_por_semana_${cutoff.year-1}.xlsx'`,fields:'files(id,name,size,modifiedTime,mimeType)'});if(references.files.length===1){const file=references.files[0],buffer=await download(userId,file);const previous=parseSnapshot('VALIDACIONES',await validationReferenceCsv(buffer),cutoff).filter(r=>r.year===cutoff.year-1);rows=[...previous,...rows].sort((a,b)=>weekKey(a)-weekKey(b));provenance.push({id:file.id,name:file.name,hash:createHash('sha256').update(buffer).digest('hex'),modifiedTime:file.modifiedTime||null});}else if(references.files.length>1)warnings.push('Referencia del año anterior duplicada.');}}
 }
 if(!rows.length)throw new Error('No hay datos históricos válidos para importar.');
 // Replace the snapshot atomically: importing again never adds the same totals twice.
 await db().historicalDataset.upsert({where:{userId_source:{userId,source}},create:{userId,source,folderId:folder.folderId,rows:JSON.parse(JSON.stringify(rows)),provenance,warnings},update:{folderId:folder.folderId,rows:JSON.parse(JSON.stringify(rows)),provenance,warnings,importedAt:new Date()}});
 return {weeks:rows.length,warnings};
}
