import 'server-only';
import {Pool} from 'pg';
import {db} from './db';
import {accessToken,driveRequest} from './drive';
import {upload} from './weekly';
import {hash} from '@/lib/weekly-model';
export async function saveReportToDrive(userId:string,id:string){const report=await db().weeklyReport.findFirst({where:{id,userId}});if(!report)throw new Error('Reporte no disponible.');const folder=await db().driveFolder.findUnique({where:{userId_type:{userId,type:'REPORTES'}}});if(!folder)throw new Error('Configura la carpeta REPORTES antes de guardar.');const account=await db().account.findFirst({where:{userId,provider:'google'}});if(!account?.scope?.split(' ').includes('https://www.googleapis.com/auth/drive.file'))throw new Error('Vuelve a autorizar Google para guardar archivos.');const resource={id:folder.folderId,key:folder.resourceKey||undefined};const metadata=await driveRequest<{capabilities?:{canAddChildren?:boolean}}>(userId,`files/${folder.folderId}`,{fields:'capabilities(canAddChildren)',supportsAllDrives:'true'},resource);if(!metadata.capabilities?.canAddChildren)throw new Error('Necesitas permiso de editor en la carpeta REPORTES.');
 const pool=new Pool({connectionString:process.env.DATABASE_URL,max:1,connectionTimeoutMillis:15000});const connection=await pool.connect().catch(async error=>{await pool.end();throw error;});try{await connection.query('BEGIN');const lock=await connection.query('SELECT pg_try_advisory_xact_lock(hashtextextended($1,0)) AS locked',[`report:${folder.folderId}:${report.fingerprint}`]);if(!lock.rows[0].locked)throw new Error('Este reporte ya se está guardando. Reintenta al terminar.');const name=`Credencializacion_Semana${report.week}_${report.year}_${report.fingerprint.slice(0,8)}.pptx`;const fileId=await upload(userId,await accessToken(userId),folder.folderId,resource.key,name,Buffer.from(report.pptx),'application/vnd.openxmlformats-officedocument.presentationml.presentation',hash(`report:${report.fingerprint}`));return {fileId,name,url:`https://drive.google.com/file/d/${fileId}/view`};}finally{try{await connection.query('ROLLBACK');}finally{connection.release();await pool.end();}}
}
