import 'server-only';
import {db} from './db';
import {hash,checkedPeriod,weeklySources,type WeeklySource} from '../weekly-model';
import {CHUNK_BYTES,MAX_PROCESS_BYTES,chunkLength} from '../upload-limits';
import {processWeekly} from './weekly';
export async function beginUpload(userId:string,value:{source:WeeklySource;year:number;week:number;name:string;size:number;digest:string}){
 if(!weeklySources.includes(value.source))throw new Error('Fuente inválida.');const period=checkedPeriod(value.year,value.week);if(typeof value.name!=='string'||value.name.length>200||!value.name.length||!Number.isSafeInteger(value.size)||value.size<1||value.size>MAX_PROCESS_BYTES||!/^[a-f0-9]{64}$/.test(value.digest))throw new Error('Archivo inválido o mayor de 50 MB.');const extensions=value.source==='OXXO'?['dat']:['xlsx','csv'];if(!extensions.includes(value.name.split('.').at(-1)?.toLowerCase()||''))throw new Error('Tipo de archivo no admitido para esta fuente.');
 const folder=await db().driveFolder.findUnique({where:{userId_type:{userId,type:value.source}}});if(!folder)throw new Error('Configura primero la carpeta de esta fuente.');
 return db().$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`upload:${userId}`},0))::text AS lock`;await tx.weeklyUpload.deleteMany({where:{expiresAt:{lt:new Date()}}});const active=await tx.weeklyUpload.aggregate({where:{userId},_sum:{size:true},_count:true});if((active._sum.size||0)+value.size>MAX_PROCESS_BYTES||active._count>=8)throw new Error('Ya hay 50 MB u ocho archivos pendientes. Termina la carga anterior o espera a su caducidad.');const upload=await tx.weeklyUpload.create({data:{source:value.source,name:value.name,size:value.size,digest:value.digest,...period,userId,folderId:folder.folderId,expiresAt:new Date(Date.now()+24*60*60*1000)},select:{id:true}});return {...upload,chunkBytes:CHUNK_BYTES};});
}
export async function putChunk(userId:string,id:string,part:number,data:Buffer){const upload=await db().weeklyUpload.findFirst({where:{id,userId,expiresAt:{gt:new Date()}}});if(!upload)throw new Error('La carga temporal no está disponible. Selecciona de nuevo los archivos.');if(data.length!==chunkLength(upload.size,part))throw new Error('Fragmento incompleto. Reintenta la carga.');const digest=hash(data);await db().$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`upload:${id}`},0))::text AS lock`;const existing=await tx.weeklyUploadChunk.findUnique({where:{uploadId_part:{uploadId:id,part}}});if(existing){if(existing.digest!==digest)throw new Error('El fragmento ya recibido tiene otro contenido.');return;}await tx.weeklyUploadChunk.create({data:{uploadId:id,part,digest,data:new Uint8Array(data)}});});}
export async function processUploads(userId:string,source:WeeklySource,year:number,week:number,ids:string[]){if(!weeklySources.includes(source)||!Array.isArray(ids)||!ids.length||ids.length>8||ids.some(id=>typeof id!=='string')||new Set(ids).size!==ids.length)throw new Error('Lote de archivos inválido.');const period=checkedPeriod(year,week),uploads=await db().weeklyUpload.findMany({where:{id:{in:ids},userId,source,...period,expiresAt:{gt:new Date()}},include:{chunks:{orderBy:{part:'asc'}}}});if(uploads.length!==ids.length)throw new Error('La carga temporal no está disponible. Selecciona de nuevo los archivos.');if(uploads.reduce((sum,u)=>sum+u.size,0)>MAX_PROCESS_BYTES)throw new Error('El lote excede 50 MB.');const folder=await db().driveFolder.findUnique({where:{userId_type:{userId,type:source}}});if(!folder||uploads.some(u=>u.folderId!==folder.folderId))throw new Error('La carpeta cambió durante la carga. Selecciona de nuevo los archivos.');
 const files=uploads.map(u=>{if(u.chunks.length!==Math.ceil(u.size/CHUNK_BYTES)||u.chunks.some((c,i)=>c.part!==i||c.data.length!==chunkLength(u.size,i)))throw new Error('Faltan fragmentos del archivo. Reintenta la carga.');const data=Buffer.concat(u.chunks.map(c=>Buffer.from(c.data)));if(hash(data)!==u.digest)throw new Error('El archivo recibido no coincide con el original.');return {name:u.name,data};});
 const result=await processWeekly(userId,source,period,files,folder.folderId);await db().weeklyUpload.deleteMany({where:{id:{in:ids},userId}});return result;
}

export async function cancelUploads(userId:string,ids:string[]){if(!Array.isArray(ids)||ids.length>8||ids.some(id=>typeof id!=="string"))throw new Error("Lote inválido.");await db().weeklyUpload.deleteMany({where:{userId,id:{in:ids}}});}
