import 'server-only';
import {reconcileCredentials} from '@/lib/weekly-credentials';
import { Pool } from 'pg';
import { db } from './db';
import { accessToken, driveRequest } from './drive';
import { fingerprint, parseWeekly, parseFirstCardBase, cumulativeCards, weeklyCsv, hash, type InputFile, type WeeklySource } from '@/lib/weekly-model';
import { weekKey, type WeeklyRow } from '@/lib/history-model';
import { isoWeek, type IsoWeek } from '@/lib/iso-week';
import type { Prisma } from '@prisma/client';
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue;
async function downloadText(token:string,id:string,key?:string){const response=await fetch(`https://www.googleapis.com/drive/v3/files/${id}?alt=media&supportsAllDrives=true`,{headers:{Authorization:`Bearer ${token}`,...(key?{'X-Goog-Drive-Resource-Keys':`${id}/${key}`}:{})},signal:AbortSignal.timeout(20000),cache:'no-store'});if(!response.ok||!response.body)throw new Error('No fue posible leer la base histórica de validaciones.');const parts:Uint8Array[]=[];let bytes=0;for await(const part of response.body){bytes+=part.length;if(bytes>20*1024*1024)throw new Error('La base de validaciones excede 20 MB.');parts.push(part);}return new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(parts));}
export async function upload(userId:string,token:string,folderId:string,key:string|undefined,name:string,data:Buffer,mimeType:string,artifact:string){
 const result=await driveRequest<{files:{id:string}[]}>(userId,'files',{q:`trashed=false and '${folderId}' in parents and appProperties has { key='imtesArtifact' and value='${artifact}' }`,fields:'files(id)',supportsAllDrives:'true',includeItemsFromAllDrives:'true'},{id:folderId,key});if(result.files.length>1)throw new Error('Hay archivos de esta carga duplicados en Drive; revisa la carpeta.');if(result.files[0])return result.files[0].id;
 const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Upload-Content-Type':mimeType,'X-Upload-Content-Length':String(data.length),...(key?{'X-Goog-Drive-Resource-Keys':`${folderId}/${key}`}:{})};
 const start=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&supportsAllDrives=true&fields=id',{method:'POST',headers,body:JSON.stringify({name,parents:[folderId],appProperties:{imtesArtifact:artifact}}),signal:AbortSignal.timeout(15000)});
 if(!start.ok)throw new Error('Drive no permitió guardar en esta carpeta. Revisa permiso de editor y autorización de la carpeta para la aplicación.');const location=start.headers.get('location');if(!location||new URL(location).hostname!=='www.googleapis.com')throw new Error('Respuesta de carga de Drive inválida.');
 const response=await fetch(location,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':mimeType},body:new Uint8Array(data),signal:AbortSignal.timeout(120000)});if(!response.ok)throw new Error('La carga en Drive no terminó. Puedes reintentar con los mismos archivos.');const file=await response.json();if(typeof file.id!=='string')throw new Error('Drive no confirmó el archivo guardado.');return file.id as string;
}
export async function processWeekly(userId:string,source:WeeklySource,period:IsoWeek,files:InputFile[],expectedFolderId?:string){
 const folder=await db().driveFolder.findUnique({where:{userId_type:{userId,type:source}}});if(!folder)throw new Error(`Configura primero la carpeta ${source}.`);if(expectedFolderId&&expectedFolderId!==folder.folderId)throw new Error("La carpeta cambió durante la carga. Selecciona de nuevo los archivos.");
 const parsed=await parseWeekly(source,files,period,process.env.TOKEN_ENCRYPTION_KEY!);files=[...files].sort((a,b)=>hash(a.data).localeCompare(hash(b.data)));const digest=fingerprint(source,folder.folderId,period,files);
 // A database advisory lock serializes all weeks for this source/folder across server instances.
 const pool=new Pool({connectionString:process.env.DATABASE_URL,max:1,connectionTimeoutMillis:15000});const connection=await pool.connect().catch(async error=>{await pool.end();throw error;});let locked=false;
 try{await connection.query('BEGIN');const result=await connection.query('SELECT pg_try_advisory_xact_lock(hashtextextended($1,0)) AS locked',[`${source}:${folder.folderId}`]);locked=result.rows[0].locked;if(!locked)throw new Error('Esta fuente ya se está procesando. Espera a que termine y vuelve a intentarlo.');
 const key={userId,source,folderId:folder.folderId,year:period.year,week:period.week};const previous=await db().weeklyImport.findUnique({where:{userId_source_folderId_year_week:key}});if(previous&&previous.fingerprint!==digest)throw new Error('Ya hay una carga distinta de esta semana. No se reemplaza automáticamente; revisa los archivos.');if(previous?.status==='complete')return {...previous.result as object,duplicate:true};
 const dataset=await db().historicalDataset.findUnique({where:{userId_source:{userId,source}}});if(dataset&&dataset.folderId!==folder.folderId)throw new Error('El histórico pertenece a otra carpeta. Revisa la configuración antes de cargar.');const oldRows=(dataset?.rows||[]) as unknown as WeeklyRow[];
 if(!previous&&oldRows.some(r=>weekKey(r)===weekKey(period)))throw new Error('Esta semana ya está en el histórico. La carga se detuvo para evitar duplicarla.');
 if(oldRows.some(r=>weekKey(r)>weekKey(period)))throw new Error('Carga las semanas en orden; esta semana es anterior al corte existente.');
 if(source==='CREDENCIALIZACION'){reconcileCredentials(oldRows,parsed.snapshot,period);if(period.week>1&&!oldRows.some(r=>r.year===period.year&&r.week===period.week-1))throw new Error('Falta la semana anterior en credencialización. Completa el histórico primero.');}
 if(source==='VALIDACIONES'&&period.week>1&&!oldRows.some(r=>r.year===period.year&&r.week===period.week-1))throw new Error('Falta la semana anterior en validaciones. Completa el histórico primero.');
 const account=await db().account.findFirst({where:{userId,provider:'google'}});if(!account?.scope?.split(' ').includes('https://www.googleapis.com/auth/drive.file'))throw new Error('La sesión no tiene permiso de carga en Drive. Vuelve a autorizar Google desde Configuración.');
 const metadata=await driveRequest<{capabilities?:{canAddChildren?:boolean}}>(userId,`files/${folder.folderId}`,{fields:'capabilities(canAddChildren)',supportsAllDrives:'true'},{id:folder.folderId,key:folder.resourceKey||undefined});if(!metadata.capabilities?.canAddChildren)throw new Error(`No tienes permiso de editor en la carpeta ${source}.`);
 const token=await accessToken(userId);let allCards=await db().validationCard.findMany({where:{userId,folderId:folder.folderId,year:period.year},select:{cardHash:true,firstDate:true}});let bootstrap=false;
 if(source==='VALIDACIONES'){
 if(!allCards.length&&oldRows.some(r=>r.year===period.year)){const name=`primera_validacion_por_tarjeta_BEA_${period.year}.csv`;const base=await driveRequest<{files:{id:string;resourceKey?:string}[]}>(userId,'files',{q:`trashed=false and '${folder.folderId}' in parents and name='${name}'`,fields:'files(id,resourceKey)',supportsAllDrives:'true',includeItemsFromAllDrives:'true'},{id:folder.folderId,key:folder.resourceKey||undefined});if(base.files.length!==1)throw new Error(`Se necesita una sola base ${name} para contar tarjetas únicas sin duplicarlas.`);allCards=parseFirstCardBase(await downloadText(token,base.files[0].id,base.files[0].resourceKey),period.year,process.env.TOKEN_ENCRYPTION_KEY!);const last=oldRows.filter(r=>r.year===period.year).at(-1);if(last&&allCards.some(c=>weekKey(isoWeek(new Date(c.firstDate+'T00:00:00Z')))>weekKey(last)))throw new Error('La base de primera validación contiene semanas posteriores al histórico. Sincroniza ambos antes de cargar.');bootstrap=true;}
 const map=new Map(allCards.map(c=>[c.cardHash,c]));const prior=cumulativeCards(allCards,period.year,period.week-1);for(const row of oldRows.filter(r=>r.year===period.year)){if(prior.find(r=>r.week===row.week)?.count!==row.count)throw new Error('La base de primera validación no coincide con el histórico. Se detuvo la carga para evitar cifras incorrectas.');}
 for(const card of parsed.cards){const old=map.get(card.cardHash);if(!old||old.firstDate>card.firstDate)map.set(card.cardHash,card);}allCards=[...map.values()];parsed.row.count=cumulativeCards(allCards,period.year,period.week).at(-1)!.count;
 }
 const rows=[...oldRows.filter(r=>weekKey(r)!==weekKey(period)),parsed.row].sort((a,b)=>weekKey(a)-weekKey(b));await db().weeklyImport.upsert({where:{userId_source_folderId_year_week:key},create:{...key,fingerprint:digest},update:{}});
 const artifacts:{id:string;name:string;hash:string}[]=[];for(const [i,file] of files.entries()){const extension=file.name.split('.').at(-1)!.toLowerCase(),name=`${source}_${period.year}_S${period.week}_${digest.slice(0,12)}_${i+1}.${extension}`;const id=await upload(userId,token,folder.folderId,folder.resourceKey||undefined,name,file.data,extension==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/plain',hash(`${digest}:original:${i}`));artifacts.push({id,name,hash:hash(file.data)});}
 for(const [label,text] of [['optimizado',parsed.optimizedCsv],['consolidado',weeklyCsv(source,rows)]]){const name=`${source}_${label}_${period.year}_S${period.week}_${digest.slice(0,12)}.csv`,data=Buffer.from(text);const id=await upload(userId,token,folder.folderId,folder.resourceKey||undefined,name,data,'text/csv',hash(`${digest}:${label}`));artifacts.push({id,name,hash:hash(data)});}
 const summary={source,year:period.year,week:period.week,records:parsed.records,count:parsed.row.count,amountCents:parsed.row.amountCents,files:artifacts.map(a=>({id:a.id,name:a.name})),duplicate:false};
 await db().$transaction(async tx=>{
 if(source==='VALIDACIONES'){const changed=bootstrap?allCards:parsed.cards;for(let i=0;i<changed.length;i+=1000)await tx.validationCard.createMany({data:changed.slice(i,i+1000).map(c=>({...c,userId,folderId:folder.folderId,year:period.year})),skipDuplicates:true});}
 const priorProvenance=Array.isArray(dataset?.provenance)?dataset.provenance:[];const provenance=json([...priorProvenance,...artifacts]);await tx.historicalDataset.upsert({where:{userId_source:{userId,source}},create:{userId,source,folderId:folder.folderId,rows:json(rows),provenance,warnings:[]},update:{rows:json(rows),provenance,importedAt:new Date()}});await tx.weeklyImport.update({where:{userId_source_folderId_year_week:key},data:{status:'complete',result:json(summary)}});
 },{timeout:60000});return summary;
 }finally{try{await connection.query('ROLLBACK');}finally{connection.release();await pool.end();}}
}
