'use client';
import {useEffect,useRef,useState} from 'react';
import type {PDFDocumentProxy,PDFDocumentLoadingTask,RenderTask} from 'pdfjs-dist';
const titles=['Portada','Credencialización','Credencialización por perfil','Ingreso electrónico','Uso de tarjetas','Contraportada'];
export function ReportPreview({reportId}:{reportId:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const [document,setDocument]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(1),[rendering,setRendering]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false,task:PDFDocumentLoadingTask|undefined;void(async()=>{try{const pdfjs=await import('pdfjs-dist');if(cancelled)return;const assets=`/pdf-assets/${pdfjs.version}/`;pdfjs.GlobalWorkerOptions.workerSrc=assets+'pdf.worker.min.mjs';task=pdfjs.getDocument({url:`/api/reportes/${reportId}/pdf`,withCredentials:true,standardFontDataUrl:assets+'standard_fonts/',cMapUrl:assets+'cmaps/',cMapPacked:true,wasmUrl:assets+'wasm/'});const result=await task.promise;if(!cancelled)setDocument(result);}catch{if(!cancelled){setError('No fue posible cargar la vista previa. Puedes reintentar o descargar el PDF.');setRendering(false);}}})();return()=>{cancelled=true;void task?.destroy();};},[reportId]);
 useEffect(()=>{if(!document)return;let cancelled=false,task:RenderTask|undefined;void(async()=>{try{const pdfPage=await document.getPage(page);if(cancelled||!canvas.current)return;const viewport=pdfPage.getViewport({scale:1.5});canvas.current.width=viewport.width;canvas.current.height=viewport.height;task=pdfPage.render({canvas:canvas.current,viewport});await task.promise;if(!cancelled)setRendering(false);}catch{if(!cancelled){setRendering(false);setError('No fue posible mostrar esta página. Descarga el PDF para revisarla.');}}})();return()=>{cancelled=true;task?.cancel();};},[document,page]);
 function choose(value:number){if(value===page)return;setError('');setRendering(true);setPage(value);}
 return <><div className="report-pdf-stage" aria-busy={rendering}><canvas ref={canvas} className="report-pdf-canvas" role="img" aria-label={`Página ${page}: ${titles[page-1]||'Reporte'}`}/>{rendering&&<p className="report-preview-loading" role="status">Cargando página…</p>}{error&&<p className="report-preview-placeholder" role="alert">{error}</p>}</div><div className="report-preview-controls"><button className="button outline small" type="button" disabled={!document||page===1||rendering} onClick={()=>choose(page-1)}>Anterior</button><p aria-live="polite">Página {page} de {document?.numPages||6} · {titles[page-1]}</p><button className="button outline small" type="button" disabled={!document||page===document.numPages||rendering} onClick={()=>choose(page+1)}>Siguiente</button></div><div className="report-preview-tabs" aria-label="Páginas del reporte">{titles.map((title,i)=><button key={title} type="button" disabled={!document||rendering} aria-pressed={page===i+1} onClick={()=>choose(i+1)}>{i+1}. {title}</button>)}</div></>;
}
