import test from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import { causRows,credentialRows,credentialConsolidatedCsv } from '../lib/history-excel';
const cutoff={year:2026,week:40};
async function caus(start:Date,end:Date){const w=new ExcelJS.Workbook(),s=w.addWorksheet('Reporte');s.addRow(['Fecha Inicio',start]);s.addRow(['Fecha Fin',end]);s.addRow(['Punto de Venta','Venta cantidad','Venta monto','Recarga cantidad','Recarga monto']);s.addRow(['A',2,10.25,3,20.10]);s.addRow(['Totales',2,10.25,3,20.10]);return Buffer.from(await w.xlsx.writeBuffer());}
test('CAUS adds sales and reload amounts without including Totales twice',async()=>{const row=await causRows(await caus(new Date('2026-09-28Z'),new Date('2026-10-04Z')),cutoff);assert.equal(row!.amountCents,3035);assert.equal(row!.week,40);});
test('CAUS rejects periods crossing ISO weeks, and excludes open weeks',async()=>{await assert.rejects(causRows(await caus(new Date('2026-09-28Z'),new Date('2026-10-10Z')),cutoff),/más de una semana/);assert.equal(await causRows(await caus(new Date('2026-10-05Z'),new Date('2026-10-11Z')),cutoff),null);});
test('credential report excludes total establishment and total profile',async()=>{const w=new ExcelJS.Workbook(),s=w.addWorksheet('BEA');s.getCell('A2').value='Del: 28/09/2026 00:00:00.000 Al: 04/10/2026 23:59:59.000';s.getCell('F7').value='UNISON';s.getCell('G7').value='TOTAL GENERAL';s.getCell('A10').value='ESTUDIANTE';s.getCell('F10').value=2;s.getCell('G10').value=2;s.getCell('A11').value='TOTAL GENERAL';s.getCell('F11').value=2;const row=await credentialRows(Buffer.from(await w.xlsx.writeBuffer()),cutoff);assert.equal(row!.count,2);assert.equal(row!.profiles!.ESTUDIANTE,2);});
test('CAUS merged quantities do not become money and date labels use their right-hand date',async()=>{const w=new ExcelJS.Workbook(),s=w.addWorksheet('Reporte');s.addRow(['Fecha Inicio',new Date('2026-09-28Z'),'Fecha Fin',new Date('2026-10-04Z')]);s.addRow(['Punto de Venta']);s.getCell('A3').value='CENTRO';s.mergeCells('B3:E3');s.getCell('B3').value=141;s.mergeCells('F3:H3');s.getCell('F3').value=4402;s.mergeCells('I3:L3');s.getCell('I3').value=457;s.mergeCells('M3:P3');s.getCell('M3').value=47722;s.getCell('A4').value='Totales';const row=await causRows(Buffer.from(await w.xlsx.writeBuffer()),cutoff);assert.equal(row!.amountCents,5212400);});

test('movement consolidated becomes weekly profile totals without card identifiers',async()=>{const w=new ExcelJS.Workbook(),s=w.addWorksheet('long_consolidado');s.addRow(['Establecimiento','Clase','anio_iso','semana_iso','Tarjetas','Tarjeta']);s.addRow(['CENTRO','ESTUDIANTE',2026,40,1,'PRIVATE_CARD_A']);s.addRow(['CENTRO','ESTUDIANTE',2026,40,1,'PRIVATE_CARD_B']);const csv=await credentialConsolidatedCsv(Buffer.from(await w.xlsx.writeBuffer()));assert.ok(!csv.includes('PRIVATE_CARD'));const {parseSnapshot}=await import('../lib/history-model');const rows=parseSnapshot('CREDENCIALIZACION',csv,cutoff);assert.equal(rows[0].count,2);assert.equal(rows[0].profiles!.ESTUDIANTE,2);});
