import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import JSZip from 'jszip';
import ExcelJS from 'exceljs';
import {reportModel,cutoffDate} from '../lib/reports/model';
import {buildWeeklyPptx} from '../lib/reports/pptx';
import type {DatasetView} from '../lib/history-model';
const period={year:2026,week:2};
function datasets():DatasetView[]{const base={warnings:[],importedAt:'2026-01-12T00:00:00Z'};return [{...base,source:'CREDENCIALIZACION',rows:[{year:2025,week:52,count:100,amountCents:0,profiles:{PREPAGO:100}},{year:2026,week:1,count:10,amountCents:0,profiles:{ESTUDIANTE:10}},{year:2026,week:2,count:20,amountCents:0,profiles:{ESTUDIANTE:20}}]},{...base,source:'VALIDACIONES',rows:[{year:2025,week:2,count:80,amountCents:0},{year:2026,week:1,count:70,amountCents:0},{year:2026,week:2,count:85,amountCents:0}]},{...base,source:'OXXO',rows:[{year:2026,week:1,count:1,amountCents:1255},{year:2026,week:2,count:1,amountCents:1555}]},{...base,source:'CAUS',rows:[{year:2026,week:1,count:0,amountCents:3055},{year:2026,week:2,count:0,amountCents:125}]}];}
test('report uses previous emission base, last unique cumulative count and exact income',()=>{const model=reportModel(datasets(),period);assert.equal(model.totals.emitted,130);assert.equal(model.totals.weeklyEmitted,20);assert.equal(model.totals.used,85);assert.equal(model.totals.previousUsed,80);assert.equal(model.totals.incomeCents,5990);assert.equal(model.totals.weeklyIncomeCents,1680);assert.deepEqual(model.charts[0].series[0].values,[110,130]);assert.match(model.text.USAGE,/65.4%/);assert.equal(cutoffDate({year:2026,week:1}),'2026-01-04');assert.equal(cutoffDate({year:2026,week:40}),'2026-10-04');});
test('partial coverage, warnings and open weeks stop report generation',()=>{const missing=datasets();missing[2].rows.pop();assert.throws(()=>reportModel(missing,period),/Falta OXXO/);const warnings=datasets();warnings[0].warnings=['Revisar archivo'];assert.throws(()=>reportModel(warnings,period),/advertencias/);assert.throws(()=>reportModel(datasets(),{year:2026,week:41},new Date('2026-10-06T12:00Z')),/cerradas/);});
test('mismatched profiles and decreasing unique counts cannot become reports',()=>{const wrong=datasets();wrong[0].rows[0].profiles!.PREPAGO=99;assert.throws(()=>reportModel(wrong,period),/no coinciden/);const used=datasets();used[1].rows[2].count=50;assert.throws(()=>reportModel(used,period),/disminuye/);});
test('missing previous reference remains a chart gap and no comparison is invented',()=>{const rows=datasets();rows[1].rows=rows[1].rows.filter(r=>r.year===2026);const model=reportModel(rows,period);assert.equal(model.totals.previousUsed,null);assert.deepEqual(model.charts[3].series[0].values,[null,null]);assert.match(model.text.USAGE,/Sin referencia/);});
test('PPTX has six slides, four editable charts and matching embedded workbook values',async()=>{const model=reportModel(datasets(),period);const result=await buildWeeklyPptx(await readFile('lib/reports/template.pptx'),model);const zip=await JSZip.loadAsync(result);assert.equal(zip.file(/^ppt\/slides\/slide\d+\.xml$/).length,6);assert.equal(zip.file(/^ppt\/slides\/charts\/chart\d+\.xml$/).length,4);const slide=await zip.file('ppt/slides/slide2.xml')!.async('string');assert.ok(slide.includes('20 credenciales'));assert.ok(!slide.includes('{{'));assert.ok(!slide.includes('140,283'));for(let i=0;i<4;i++){const chart=await zip.file(`ppt/slides/charts/chart${i+1}.xml`)!.async('string');assert.ok(chart.includes(`$A$${model.charts[i].categories.length+1}`));const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await zip.file(`ppt/embeddings/chart-data-snapshot-${String(i+1).padStart(3,'0')}.xlsx`)!.async('nodebuffer') as never);const s=workbook.getWorksheet('Chart Data')!;assert.equal(s.getCell('B1').value,model.charts[i].series[0].name);assert.equal(s.getCell('B2').value,model.charts[i].series[0].values[0]);assert.equal(s.getCell('B3').value,model.charts[i].series[0].values[1]);}});
test('Government cards remain in the total and appear without an invented goal',()=>{const d=datasets();d[0].rows[0].count=102;d[0].rows[0].profiles!.GOBIERNO=2;const model=reportModel(d,period);assert.equal(model.totals.emitted,132);assert.equal(model.totals.profiles.GOBIERNO,2);const index=model.charts[1].categories.indexOf('GOBIERNO');assert.equal(model.charts[1].series[0].values[index],2);assert.ok(!model.charts[1].series[1].categories!.includes('GOBIERNO'));assert.match(model.text.PROFILES,/GOBIERNO: 2/);});

test('PDF preserves six pages and the report cutoff metadata',async()=>{const {buildReportPdf}=await import('../lib/reports/pdf');const {PDFDocument}=await import('pdf-lib');const fs=await import('node:fs/promises');const logo=await fs.readFile('public/branding/logo-imtes-2026.png');const doc=await PDFDocument.load(await buildReportPdf(reportModel(datasets(),period),logo));assert.equal(doc.getPageCount(),6);assert.match(doc.getTitle()||'',/Semana 2/);});

test('saved goals reach both chart series and frozen report goals',()=>{const goals={PREPAGO:120,ESTUDIANTE:50,'TERCERA EDAD':8,DISCAPACIDAD:4,general:200};const model=reportModel(datasets(),period,new Date(),goals);assert.deepEqual(model.charts[0].series[1].values,[200,200]);assert.deepEqual(model.charts[1].series[1].values,[120,50,8,4]);assert.deepEqual(model.goals,goals);goals.general=300;assert.equal(model.goals.general,200);});
