'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {LockKeyhole,Save,RotateCcw} from 'lucide-react';
import {defaultGoals} from '@/lib/config/defaults';
import type {GoalSettings} from '@/lib/config/goals';
import {StatusBadge} from './StatusBadge';
import {DriveSettings} from '@/components/drive/drive-settings';
import type {DriveState} from '@/lib/drive-model';
export function SettingsWorkspace({drive,settings}:{drive:DriveState;settings:GoalSettings}){
 const router=useRouter();const [saved,setSaved]=useState(settings),[values,setValues]=useState<Record<string,string>>(Object.fromEntries(Object.entries(settings.goals).map(([key,value])=>[key,String(value)]))),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const dirty=Object.entries(saved.goals).some(([key,value])=>values[key]!==String(value));
 async function reload(){setBusy(true);setError('');try{const response=await fetch('/api/configuracion/metas');if(!response.ok)throw new Error('No fue posible recargar las metas.');const latest:GoalSettings=await response.json();setSaved(latest);setValues(Object.fromEntries(Object.entries(latest.goals).map(([key,value])=>[key,String(value)])));setMessage('Se cargaron las metas guardadas de tu cuenta.');}catch(e){setError(e instanceof Error?e.message:'No fue posible recargar.');}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/configuracion/metas',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({goals:Object.fromEntries(Object.entries(values).map(([key,value])=>[key,Number(value)])),version:saved.version})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSaved(result);setValues(Object.fromEntries(Object.entries(result.goals).map(([key,value])=>[key,String(value)])));setMessage('Metas guardadas. Dashboard y nuevos reportes usarán estos valores.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar.');}finally{setBusy(false);}}
 return <><section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">GENERAL</span><h2>Metas de credencialización</h2><p>Metas de tu cuenta. Se conservan al salir y recargar.</p></div><StatusBadge>{dirty?'Cambios sin guardar':saved.version?'Metas guardadas':'Metas iniciales'}</StatusBadge></div><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="goals-fieldset"><div className="goals-grid">{Object.entries(values).map(([profile,value])=><label key={profile}>{profile==='general'?'Meta general histórica':profile}<input required type="number" inputMode="numeric" min={1} max={1000000000} step={1} value={value} onChange={e=>{setValues(previous=>({...previous,[profile]:e.target.value}));setMessage('');setError('');}}/></label>)}</div><div className="settings-bottom"><p>Guardar actualiza el dashboard y los reportes que generes después. Los anteriores conservan sus metas.</p><button type="button" className="button outline" onClick={()=>{setValues(Object.fromEntries(Object.entries(defaultGoals).map(([key,value])=>[key,String(value)])));setMessage('Valores iniciales cargados. Pulsa Guardar metas para conservarlos.');setError('');}}><RotateCcw size={15}/>Restablecer</button><button className="button primary" type="submit" disabled={!dirty&&saved.version>0}><Save size={15}/>{busy?'Guardando…':'Guardar metas'}</button></div></fieldset>{error&&<p role="alert" className="error-text">{error} <button type="button" className="table-link" disabled={busy} onClick={()=>void reload()}>Recargar metas guardadas</button></p>}<p role="status" className="settings-message">{message}</p></form></section><DriveSettings state={drive}/><div className="notice"><LockKeyhole size={19}/><p><strong>Acceso seguro con OAuth.</strong> La plataforma no solicita contraseñas de Google. Los secretos y tokens se gestionan del lado del servidor.</p></div></>;
}
