import ExcelJS from 'exceljs';
import { isoWeek, type IsoWeek } from './iso-week';
import { dateValue, weekKey, included, type WeeklyRow } from './history-model';
function unmerge(workbook:ExcelJS.Workbook){for(const sheet of workbook.worksheets){for(const range of [...(sheet.model.merges||[])])sheet.unMergeCells(range);}}
function cell(value:ExcelJS.CellValue):unknown {if(value&&typeof value==='object'){if('result'in value)return value.result;if('richText'in value)return value.richText.map(v=>v.text).join('');}return value;}
export async function causRows(buffer:Buffer,cutoff:IsoWeek){const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer as unknown as Parameters<typeof workbook.xlsx.load>[0]);unmerge(workbook);const ws=workbook.worksheets[0];if(!ws)throw new Error('Excel sin hoja.');let start:Date|null=null,end:Date|null=null,header=0,pv=0;
 ws.eachRow(row=>row.eachCell((c,index)=>{const value=cell(c.value);if(typeof value!=='string')return;const label=value.trim().toLowerCase();if(label.startsWith('fecha inicio')||label.startsWith('fecha fin')){let found:Date|null=null;for(let j=index+1;j<=row.cellCount;j++){found=dateValue(cell(row.getCell(j).value));if(found)break;}if(label.startsWith('fecha inicio'))start=found;else end=found;}if(label==='punto de venta'){header=row.number;pv=index;}}));
 if(!start||!end||!header||!pv)throw new Error('No se detectaron fechas o Punto de Venta.');const from=isoWeek(start),to=isoWeek(end);const row:WeeklyRow={...from,count:0,amountCents:0};if(!included(row,cutoff))return null;if(weekKey(from)!==weekKey(to))throw new Error('El periodo abarca más de una semana; requiere revisión antes de asignar ingreso.');
 let first=0;for(let r=header+1;r<=ws.rowCount;r++){const name=cell(ws.getRow(r).getCell(pv).value);if(typeof name==='string'&&name.trim()&&!/^(totales|tarjetas vendidas:|recargas realizadas:|recargas de pases:)$/i.test(name.trim())){first=r;break;}}
 const cols:number[]=[];ws.getRow(first).eachCell((c,index)=>{const v=cell(c.value);if(index>pv&&v!==null&&v!==''&&typeof v!=='object'&&Number.isFinite(Number(String(v).replace(/,/g,''))))cols.push(index);});if(cols.length<4)throw new Error('Faltan columnas de montos.');
 for(let r=first;r<=ws.rowCount;r++){const values=ws.getRow(r),name=cell(values.getCell(pv).value);if(typeof name==='string'&&name.trim().toLowerCase()==='totales')break;if(typeof name!=='string'||!name.trim())continue;for(const index of [cols[1],cols[3]]){const v=cell(values.getCell(index).value);const amount=v===null?0:Number(String(v).replace(/,/g,''));if(!Number.isFinite(amount)||amount<0)throw new Error('Monto CAUS inválido.');row.amountCents+=Math.round(amount*100);}}
 return row;
}
export async function credentialRows(buffer:Buffer,cutoff:IsoWeek){
 const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer as unknown as Parameters<typeof workbook.xlsx.load>[0]);unmerge(workbook);const ws=workbook.worksheets[0];if(!ws)throw new Error('Excel sin hoja.');let period='';ws.eachRow(row=>row.eachCell(c=>{const value=cell(c.value);if(typeof value==='string'&&/Del:/.test(value)&&/Al:/.test(value))period=value;}));
 const start=dateValue(period.slice(period.indexOf('Del:')+4)),end=dateValue(period.slice(period.indexOf('Al:')+3));if(!start||!end)throw new Error('No se detectó el periodo de emisión.');const from=isoWeek(start);const result:WeeklyRow={...from,count:0,amountCents:0,profiles:{}};if(!included(result,cutoff))return null;if(weekKey(from)!==weekKey(isoWeek(end)))throw new Error('El periodo de emisión abarca más de una semana.');
 const columns:number[]=[];for(let c=6;c<=ws.columnCount;c++){const value=cell(ws.getRow(7).getCell(c).value);if(!value)continue;if(/^(TOTAL GENERAL|GRAND TOTAL)$/i.test(String(value).trim()))break;columns.push(c);}if(!columns.length)throw new Error('No se detectaron establecimientos en fila 7.');
 let began=false;for(let r=1;r<=ws.rowCount;r++){const name=cell(ws.getRow(r).getCell(1).value);if(!began&&typeof name==='string'&&['DISCAPACITADO','DISCAPACIDAD','ESTUDIANTE','PREPAGO','TARIFA GENERAL','TERCERA EDAD','GOBIERNO'].includes(name.trim().toUpperCase()))began=true;if(!began)continue;if(!name||/^(TOTAL GENERAL|GRAND TOTAL)$/i.test(String(name).trim()))break;const profile=String(name).trim();let count=0;for(const c of columns){const value=cell(ws.getRow(r).getCell(c).value);const n=value===null?0:Number(value);if(!Number.isSafeInteger(n)||n<0)throw new Error('Conteo de emisión inválido.');count+=n;}result.profiles![profile]=count;result.count+=count;}
 if(!began)throw new Error('No se detectaron perfiles de emisión.');return result;
}
export async function credentialConsolidatedCsv(buffer:Buffer){
 const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer as unknown as Parameters<typeof workbook.xlsx.load>[0]);const sheet=workbook.getWorksheet('long_consolidado');if(!sheet)throw new Error('No está la hoja long_consolidado.');const quote=(value:unknown)=>'"'+String(value??'').replace(/"/g,'""')+'"';const headers=Array.from({length:sheet.columnCount},(_,i)=>String(cell(sheet.getRow(1).getCell(i+1).value)||''));
 if(headers.includes('Clase')){const index=(name:string)=>headers.indexOf(name)+1;const groups=new Map<string,{year:number;week:number;profile:string;site:string;count:number}>();for(let r=2;r<=sheet.rowCount;r++){const row=sheet.getRow(r),year=Number(cell(row.getCell(index('anio_iso')).value)),week=Number(cell(row.getCell(index('semana_iso')).value)),profile=String(cell(row.getCell(index('Clase')).value)),site=String(cell(row.getCell(index('Establecimiento')).value));const count=Number(cell(row.getCell(index('Tarjetas')).value));if(!Number.isSafeInteger(count)||count<0)throw new Error('Conteo de emisión inválido.');const key=JSON.stringify([year,week,profile,site]),group=groups.get(key)||{year,week,profile,site,count:0};group.count+=count;groups.set(key,group);}return ['Perfil,Establecimiento,Tarjetas,anio_iso,semana_iso,Archivo',...[...groups.values()].map(g=>[g.profile,g.site,g.count,g.year,g.week,'movimientos_consolidado'].map(quote).join(','))].join('\n');}
 const lines:string[]=[];sheet.eachRow(row=>{const values=Array.from({length:sheet.columnCount},(_,i)=>cell(row.getCell(i+1).value));lines.push(values.map(quote).join(','));});return lines.join('\n');
}
export async function validationReferenceCsv(buffer:Buffer){const w=new ExcelJS.Workbook();await w.xlsx.load(buffer as never);const rows:string[]=[];w.worksheets[0].eachRow(row=>rows.push(Array.from({length:3},(_,i)=>String(cell(row.getCell(i+1).value)??'')).join(',')));return rows.join('\n');}
