import { createHash, createHmac } from 'node:crypto';
import ExcelJS from 'exceljs';
import {checkXlsxSize} from './xlsx-limits';
import {MAX_PROCESS_BYTES} from './upload-limits';
import { parse } from 'csv-parse/sync';
import { parseCredentials } from './weekly-credentials';
import { causRows } from './history-excel';
import { dateValue, weekKey, parseSnapshot, type WeeklyRow } from './history-model';
import { isoWeek, lastClosedWeek, type IsoWeek } from './iso-week';
export type WeeklySource = 'OXXO'|'CAUS'|'VALIDACIONES'|'CREDENCIALIZACION';
export const weeklySources:WeeklySource[]=['OXXO','CAUS','VALIDACIONES','CREDENCIALIZACION'];
export const MAX_UPLOAD_BYTES=3*1024*1024;
export type InputFile={name:string;data:Buffer};
export type FirstCard={cardHash:string;firstDate:string};
export function hash(data:Buffer|string){return createHash('sha256').update(data).digest('hex');}
export function fingerprint(source:WeeklySource,folder:string,period:IsoWeek,files:InputFile[]){return hash(JSON.stringify([source,folder,period.year,period.week,files.map(f=>hash(f.data)).sort()]));}
export function checkedPeriod(year:number,week:number,now=new Date()):IsoWeek{if(!Number.isInteger(year)||year<2000||year>2100||!Number.isInteger(week)||week<1||week>isoWeek(new Date(Date.UTC(year,11,28))).week)throw new Error('Año o semana ISO inválida.');const period={year,week};if(weekKey(period)>weekKey(lastClosedWeek(now)))throw new Error('Solo se pueden procesar semanas cerradas.');return period;}
function norm(value:unknown){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');}
function value(v:ExcelJS.CellValue):unknown{if(v&&typeof v==='object'){if('result'in v)return v.result;if('richText'in v)return v.richText.map(p=>p.text).join('');}return v;}
export function csv(records:unknown[][]){return '\ufeff'+records.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n')+'\r\n';}
export function weeklyCsv(source:WeeklySource,rows:WeeklyRow[]){if(source==='CREDENCIALIZACION')return csv([['Perfil','Establecimiento','Tarjetas','anio_iso','semana_iso','Archivo'],...rows.flatMap(r=>Object.entries(r.profiles||{}).map(([profile,count])=>[profile,'CONSOLIDADO',count,r.year,r.week,'imtes_semanal']))]);return csv([source==='OXXO'?['anio_iso','semana_iso','frecuencia','monto']:source==='CAUS'?['anio_iso','semana_iso','ingreso_caus']:['Año','Semana','Tarjetas'],...rows.map(r=>source==='OXXO'?[r.year,r.week,r.count,(r.amountCents/100).toFixed(2)]:source==='CAUS'?[r.year,r.week,(r.amountCents/100).toFixed(2)]:[r.year,r.week,r.count])]);}
function inPeriod(date:Date,period:IsoWeek){if(weekKey(isoWeek(date))!==weekKey(period))throw new Error('El archivo contiene fechas fuera de la semana seleccionada.');}
function date(v:unknown):Date|null{if(v instanceof Date)return v;const s=String(v??'').trim();return dateValue(s)||dateValue(s.replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3'));}
export async function parseWeekly(source:WeeklySource,files:InputFile[],period:IsoWeek,secret:string){
 if(!files.length||files.length>8)throw new Error('Selecciona entre uno y ocho archivos.');if(files.reduce((n,f)=>n+f.data.length,0)>MAX_PROCESS_BYTES)throw new Error('El lote excede 50 MB. Divide los archivos antes de subirlos.');const hashes=files.map(f=>hash(f.data));if(new Set(hashes).size!==hashes.length)throw new Error('El mismo archivo está seleccionado dos veces.');
 const row:WeeklyRow={...period,count:0,amountCents:0};let snapshot:WeeklyRow[]|undefined;let records=0;const cards=new Map<string,FirstCard>();const optimized:unknown[][]=[['Tarjeta','Fecha_Hora']];const events=new Set<string>();
 for(const file of files){const ext=file.name.split('.').at(-1)?.toLowerCase();if(ext==='xlsx')await checkXlsxSize(file.data);if(ext==='xls')throw new Error('Guarda el archivo .xls como .xlsx antes de procesarlo.');
 if(source==='OXXO'){if(ext!=='dat')throw new Error('OXXO requiere .DAT.');const lines=parse(new TextDecoder('utf-8',{fatal:true}).decode(file.data),{bom:true,skip_empty_lines:true,trim:true}) as string[][];for(const line of lines){if(line.length!==7)throw new Error('DAT inválido: se esperan siete columnas.');const d=date(line[2]);if(!d)throw new Error('Fecha OXXO inválida.');inPeriod(d,period);const amount=Number(line[6]);if(!Number.isFinite(amount)||amount<0)throw new Error('Importe OXXO inválido.');records++;if(!line[5].slice(0,14).startsWith('04'))continue;const key=JSON.stringify(line.slice(0,6));if(events.has(key))throw new Error('Operación OXXO duplicada en el lote.');events.add(key);row.count++;row.amountCents+=Math.round(amount*100);}}
 else if(source==='CAUS'){if(files.length!==1)throw new Error('Selecciona un solo reporte CAUS por semana.');if(ext==='xlsx'){const r=await causRows(file.data,period);if(!r||weekKey(r)!==weekKey(period))throw new Error('El periodo CAUS no coincide con la semana seleccionada.');Object.assign(row,r);records=1;}else if(ext==='csv'){const rows=parseSnapshot('CAUS',new TextDecoder('utf-8',{fatal:true}).decode(file.data),{year:2100,week:52});if(rows.length!==1||weekKey(rows[0])!==weekKey(period))throw new Error('El CSV CAUS debe contener únicamente la semana seleccionada.');Object.assign(row,rows[0]);records=1;}else throw new Error('CAUS requiere .xlsx o .csv.');}
 else if(source==='CREDENCIALIZACION'){if(files.length!==1)throw new Error('Selecciona un solo reporte o consolidado de credencialización.');const parsed=await parseCredentials(file.name,file.data,period);Object.assign(row,parsed.row);records=parsed.records;snapshot=parsed.snapshot;}
 else{let table:unknown[][];if(ext==='xlsx'){const w=new ExcelJS.Workbook();await w.xlsx.load(file.data as never);const sheet=w.worksheets[0];if(!sheet)throw new Error('Excel sin hoja.');if(sheet.rowCount>250000)throw new Error('Divide el archivo de validaciones.');table=[];sheet.eachRow(r=>table.push(Array.from({length:sheet.columnCount},(_,i)=>value(r.getCell(i+1).value))));}else if(ext==='csv')table=parse(new TextDecoder('utf-8',{fatal:true}).decode(file.data),{bom:true,skip_empty_lines:true,trim:true});else throw new Error('Validaciones requiere .xlsx o .csv.');const headers=table.shift()?.map(norm)||[];const cardIndex=headers.findIndex(h=>['TARJETA','IDTARJETA','NOTARJETA','NUMEROTARJETA','NUMTARJETA'].includes(h));const dateIndex=headers.findIndex(h=>['FECHAHORA','FECHAHORAVALIDACION','FECHAHORADEVALIDACION','FECHA'].includes(h));if(cardIndex<0||dateIndex<0)throw new Error('No se detectaron las columnas Tarjeta y Fecha/Hora.');for(const line of table){if(line.every(v=>v===null||v===undefined||v===''))continue;const card=String(line[cardIndex]??'').trim(),d=date(line[dateIndex]);if(!card||!d)throw new Error('Hay tarjetas o fechas inválidas; corrige el archivo antes de procesarlo.');inPeriod(d,period);records++;const cardHash=createHmac('sha256',secret).update(`${period.year}:${card}`).digest('hex'),firstDate=d.toISOString().slice(0,10),old=cards.get(cardHash);if(!old||old.firstDate>firstDate)cards.set(cardHash,{cardHash,firstDate});optimized.push([card,firstDate]);}}
 }
 if(!records)throw new Error('El lote no contiene registros.');return {row,records,snapshot,cards:[...cards.values()],optimizedCsv:source==='VALIDACIONES'?csv(optimized):weeklyCsv(source,[row])};
}
export function parseFirstCardBase(text:string,year:number,secret:string):FirstCard[]{const rows=parse(text,{columns:true,bom:true,skip_empty_lines:true,trim:true}) as Record<string,string>[];const map=new Map<string,FirstCard>();for(const row of rows){const card=row.Tarjeta?.trim(),d=date(row.primera_validacion);if(!card||!d||isoWeek(d).year!==year)throw new Error('La base de primera validación tiene tarjetas o fechas inválidas.');const cardHash=createHmac('sha256',secret).update(`${year}:${card}`).digest('hex'),firstDate=d.toISOString().slice(0,10),old=map.get(cardHash);if(!old||old.firstDate>firstDate)map.set(cardHash,{cardHash,firstDate});}if(!map.size)throw new Error('La base histórica de tarjetas está vacía.');return [...map.values()];}
export function cumulativeCards(cards:FirstCard[],year:number,through:number):WeeklyRow[]{const counts=new Map<number,number>();for(const c of cards){const w=isoWeek(new Date(c.firstDate+'T00:00:00Z'));if(w.year===year)counts.set(w.week,(counts.get(w.week)||0)+1);}let count=0;return Array.from({length:through},(_,i)=>{count+=counts.get(i+1)||0;return {year,week:i+1,count,amountCents:0};});}
