import {validateGoals} from '@/lib/config/goals';
import type {Goals} from '@/types/domain';
import { defaultGoals } from '@/lib/config/defaults';
import { historySources, weekKey, type DatasetView } from '@/lib/history-model';
import { isoWeek, lastClosedWeek, type IsoWeek } from '@/lib/iso-week';
const profiles=['PREPAGO','ESTUDIANTE','TERCERA EDAD','DISCAPACIDAD','GOBIERNO'] as const;
export type ReportChart={title:string;categories:string[];series:{name:string;values:(number|null)[];categories?:string[]}[]};
export type ReportModel={period:IsoWeek;cutoff:string;text:Record<string,string>;charts:ReportChart[];totals:{emitted:number;weeklyEmitted:number;used:number;previousUsed:number|null;incomeCents:number;weeklyIncomeCents:number;oxxoCents:number;causCents:number;profiles:Record<string,number>};sources:{source:string;importedAt:string}[];goals:Goals};
export function cutoffDate(period:IsoWeek){const d=new Date(Date.UTC(period.year,0,4));d.setUTCDate(d.getUTCDate()-(d.getUTCDay()||7)+1+(period.week-1)*7+6);return d.toISOString().slice(0,10);}
export function reportModel(datasets:DatasetView[],period:IsoWeek,now=new Date(),savedGoals:Goals=defaultGoals):ReportModel{
 const goals=validateGoals(savedGoals);
 if(!Number.isInteger(period.year)||!Number.isInteger(period.week)||period.year<2000||period.year>2100||period.week<1||period.week>isoWeek(new Date(Date.UTC(period.year,11,28))).week)throw new Error('Periodo ISO inválido.');if(weekKey(period)>weekKey(lastClosedWeek(now)))throw new Error('Solo se generan reportes de semanas cerradas.');
 for(const source of historySources){const d=datasets.find(d=>d.source===source);if(!d)throw new Error(`Faltan datos de ${source}.`);if(d.warnings.length)throw new Error(`Revisa las advertencias de ${source} antes de generar el reporte.`);for(let week=1;week<=period.week;week++)if(!d.rows.some(r=>r.year===period.year&&r.week===week))throw new Error(`Falta ${source} en ${period.year}-S${String(week).padStart(2,'0')}.`);const keys=d.rows.map(weekKey);if(new Set(keys).size!==keys.length)throw new Error(`Hay semanas duplicadas en ${source}.`);for(const r of d.rows)if(!Number.isSafeInteger(r.count)||r.count<0||!Number.isSafeInteger(r.amountCents)||r.amountCents<0)throw new Error(`Hay cifras inválidas en ${source}.`);}
 const rows=(source:string)=>datasets.find(d=>d.source===source)!.rows.filter(r=>r.year===period.year&&r.week<=period.week).sort((a,b)=>a.week-b.week);
 const emitted=datasets.find(d=>d.source==='CREDENCIALIZACION')!.rows.filter(r=>weekKey(r)<=weekKey(period)).sort((a,b)=>weekKey(a)-weekKey(b));
 const profileCounts:Record<string,number>=Object.fromEntries(profiles.map(p=>[p,0]));for(const r of emitted){if(!r.profiles)throw new Error('Falta el detalle por perfil de credencialización.');let sum=0;for(const [name,count]of Object.entries(r.profiles)){const profile=name==='TARIFA GENERAL'?'PREPAGO':name==='DISCAPACITADO'?'DISCAPACIDAD':name;if(!profiles.includes(profile as typeof profiles[number])||!Number.isSafeInteger(count)||count<0)throw new Error('Perfil de credencialización inválido.');profileCounts[profile]+=count;sum+=count;}if(sum!==r.count)throw new Error('Los perfiles no coinciden con el total de credencialización.');}
 const oxxo=rows('OXXO'),caus=rows('CAUS'),usedRows=rows('VALIDACIONES');for(let i=1;i<usedRows.length;i++)if(usedRows[i].count<usedRows[i-1].count)throw new Error('El acumulado de tarjetas utilizadas disminuye.');
 const sum=(sourceRows:typeof oxxo,key:'count'|'amountCents')=>sourceRows.reduce((total,r)=>total+r[key],0);
 const totalEmitted=sum(emitted,'count'),weeklyEmitted=rows('CREDENCIALIZACION').at(-1)!.count,used=usedRows.at(-1)!.count,oxxoCents=sum(oxxo,'amountCents'),causCents=sum(caus,'amountCents'),incomeCents=oxxoCents+causCents,weeklyIncomeCents=oxxo.at(-1)!.amountCents+caus.at(-1)!.amountCents;
 if(used>totalEmitted)throw new Error('Las tarjetas utilizadas superan a las emitidas. Concilia las fuentes antes de generar.');
 const prior=datasets.find(d=>d.source==='VALIDACIONES')!.rows.filter(r=>r.year===period.year-1&&r.week<=period.week);const previousUsed=prior.find(r=>r.week===period.week)?.count??null;
 const number=(n:number)=>n.toLocaleString('es-MX'),money=(n:number)=>(n/100).toLocaleString('es-MX',{style:'currency',currency:'MXN'});const cutoff=cutoffDate(period);
 let accumulated=sum(emitted.filter(r=>r.year<period.year),'count');const emissionValues=rows('CREDENCIALIZACION').map(r=>accumulated+=r.count);const categories=oxxo.map(r=>'S'+String(r.week).padStart(2,'0'));
 return {period,cutoff,goals,sources:datasets.map(d=>({source:d.source,importedAt:d.importedAt})),totals:{emitted:totalEmitted,weeklyEmitted,used,previousUsed,incomeCents,weeklyIncomeCents,oxxoCents,causCents,profiles:profileCounts},text:{PERIOD:`Semana ${period.week} de ${period.year}`,CUTOFF:`Corte: ${cutoff.split('-').reverse().join('/')} · Hermosillo, Sonora`,EMISSION:`En la semana ${period.week} se emitieron ${number(weeklyEmitted)} credenciales, para alcanzar un acumulado de ${number(totalEmitted)}.`,PROFILES:profiles.map(p=>`${p}: ${number(profileCounts[p])}`).join('. ')+'.',INCOME:`Acumulado: ${money(incomeCents)}. Semana ${period.week}: ${money(weeklyIncomeCents)} (OXXO ${money(oxxo.at(-1)!.amountCents)} y CAUS ${money(caus.at(-1)!.amountCents)}).`,USAGE:`Al corte se utilizaron ${number(used)} tarjetas únicas, ${totalEmitted?(used/totalEmitted*100).toFixed(1):'0.0'}% de las emitidas.${previousUsed===null?' Sin referencia del año anterior al mismo corte.':` En ${period.year-1}: ${number(previousUsed)}.`}`},charts:[{title:'Acumulado de tarjetas emitidas',categories,series:[{name:'Tarjetas emitidas',values:emissionValues},{name:'Meta general',values:categories.map(()=>goals.general)}]},{title:'Tarjetas emitidas por perfil y meta',categories:[...profiles],series:[{name:'Tarjetas emitidas',values:profiles.map(p=>profileCounts[p])},{name:'Meta',categories:profiles.filter(p=>p!=='GOBIERNO'),values:profiles.filter(p=>p!=='GOBIERNO').map(p=>goals[p])}]},{title:`Ingreso semanal OXXO y CAUS · ${period.year}`,categories,series:[{name:'OXXO',values:oxxo.map(r=>r.amountCents/100)},{name:'CAUS',values:caus.map(r=>r.amountCents/100)}]},{title:`Tarjetas únicas utilizadas · ${period.year-1} y ${period.year}`,categories,series:[{name:String(period.year-1),values:oxxo.map(r=>prior.find(p=>p.week===r.week)?.count??null)},{name:String(period.year),values:usedRows.map(r=>r.count)}]}]};
}
