import {PDFDocument,StandardFonts,rgb,type PDFPage,type PDFFont} from 'pdf-lib';
import type {ReportModel,ReportChart} from './model';
const guinda=rgb(.58,.035,.29),orange=rgb(.89,.49,.20),gray=rgb(.48,.48,.48),white=rgb(1,1,1),black=rgb(.12,.12,.12);
function clean(s:string){return s.replace(/[\u202f\u00a0]/g,' ').replace(/[\u2010-\u2015]/g,'-');}
function text(page:PDFPage,font:PDFFont,s:string,x:number,y:number,size=14,color=black){page.drawText(clean(s),{x,y,size,font,color});}
function wrapped(page:PDFPage,font:PDFFont,s:string,x:number,y:number,width:number,size=16){let line='';for(const word of clean(s).split(/\s+/)){if(line&&font.widthOfTextAtSize(line+' '+word,size)>width){text(page,font,line,x,y,size);y-=size*1.3;line=word;}else line+=(line?' ':'')+word;}if(line)text(page,font,line,x,y,size);return y-size*1.3;}
function chart(page:PDFPage,font:PDFFont,bold:PDFFont,c:ReportChart,index:number){const left=140,bottom=100,width=745,height=205;page.drawRectangle({x:40,y:62,width:880,height:275,color:white});text(page,bold,c.title,60,315,17);
 const largest=Math.max(1,...c.series.flatMap(s=>s.values.filter((v):v is number=>v!==null))),power=10**Math.floor(Math.log10(largest)),max=Math.ceil(largest/power*2)/2*power;
 if(index===1){const barWidth=700,step=39;for(let tick=0;tick<=4;tick++){const x=190+barWidth*tick/4;page.drawLine({start:{x,y:95},end:{x,y:292},color:rgb(.90,.90,.90),thickness:.5});text(page,font,(max*tick/4).toLocaleString('es-MX',{maximumFractionDigits:0}),x-12,78,10,gray);}for(const [i,category]of c.categories.entries()){const y=278-i*step;text(page,font,category,54,y-4,11);for(const [j,series]of c.series.entries()){const idx=(series.categories||c.categories).indexOf(category),v=idx<0?null:series.values[idx];if(v===null||v===undefined)continue;const yy=y-j*12;page.drawRectangle({x:190,y:yy-9,width:barWidth*v/max,height:10,color:j?orange:guinda});text(page,bold,v.toLocaleString('es-MX'),Math.min(190+barWidth*v/max+5,898),yy-7,10);}}}
 else{for(let tick=0;tick<=4;tick++){const y=bottom+height*tick/4;page.drawLine({start:{x:left,y},end:{x:left+width,y},color:rgb(.86,.86,.86),thickness:.6});text(page,font,(index===2?'$':'')+(max*tick/4).toLocaleString('es-MX',{maximumFractionDigits:0}),55,y-4,10,gray);}const x=(i:number)=>left+i*width/Math.max(1,c.categories.length-1),y=(v:number)=>bottom+v/max*height;for(const [i,label]of c.categories.entries())if(i%Math.max(1,Math.ceil(c.categories.length/10))===0||i===c.categories.length-1)text(page,font,label,x(i)-9,82,10,gray);for(const [j,series]of c.series.entries()){const color=index===3?(j?guinda:gray):(j?orange:guinda);let prev:{x:number;y:number}|null=null;for(const [i,v]of series.values.entries()){if(v===null){prev=null;continue;}const point={x:x(i),y:y(v)};if(prev)page.drawLine({start:prev,end:point,color,thickness:1.8});page.drawCircle({x:point.x,y:point.y,size:1.5,color});prev=point;}}}
 c.series.forEach((s,j)=>{const x=330+j*210;colorLegend(page,font,s.name,x,47,index===3?(j?guinda:gray):(j?orange:guinda));});
}
function colorLegend(page:PDFPage,font:PDFFont,s:string,x:number,y:number,color:ReturnType<typeof rgb>){page.drawLine({start:{x,y:y+4},end:{x:x+20,y:y+4},color,thickness:3});text(page,font,s,x+27,y,11,gray);}
export async function buildReportPdf(model:ReportModel,logoBytes:Uint8Array){const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),logo=await doc.embedPng(logoBytes);doc.setTitle(`Credencialización - ${model.text.PERIOD}`);doc.setAuthor('IMTES');const titles=['Reporte de Credencialización','CREDENCIALIZACIÓN','CREDENCIALIZACIÓN POR PERFIL','INGRESO ELECTRÓNICO','USO DE TARJETAS','IMTES · SONORA'];const sections=['','EMISSION','PROFILES','INCOME','USAGE',''];
 for(let i=0;i<6;i++){const page=doc.addPage([960,540]);page.drawRectangle({x:0,y:0,width:960,height:540,color:i===5?guinda:rgb(.965,.965,.965)});page.drawRectangle({x:0,y:448,width:960,height:92,color:white});page.drawImage(logo,{x:30,y:455,width:260,height:81});page.drawRectangle({x:0,y:440,width:960,height:6,color:orange});text(page,font,model.text.PERIOD,710,483,15,guinda);
 if(i===0){text(page,bold,titles[i],80,290,36,guinda);text(page,font,model.text.PERIOD,80,220,28,guinda);text(page,font,model.text.CUTOFF,80,140,16);text(page,font,'Credencialización y recaudo electrónico de Hermosillo',80,105,16,gray);}
 else if(i===5){text(page,bold,'Instituto de Movilidad y Transporte',70,295,32,white);text(page,bold,'para el Estado de Sonora',70,248,32,white);text(page,font,model.text.CUTOFF,70,185,18,white);text(page,font,'Reporte generado con el corte validado de las cuatro fuentes.',70,135,16,white);}
 else{text(page,bold,titles[i],40,404,25,guinda);wrapped(page,bold,model.text[sections[i]],40,370,875,15);chart(page,font,bold,model.charts[i-1],i-1);}
 text(page,font,`${model.period.year}-S${String(model.period.week).padStart(2,'0')} · ${i+1}/6`,815,20,10,i===5?white:gray);
 }return Buffer.from(await doc.save());}
